Algoritmo "Convercao_temperatura["
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 11/01/2024
Var
   celcius, firen: real


Inicio
      escreva("Qual a temperatura? ")
      leia(firen)
      celcius<- (firen- 32) / 1.8
      escreval("A temperatura em Celcius é: ", celcius:4:2, "° graus")


Fimalgoritmo