Algoritmo "Equacao_Segundo_Grau"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 05/01/2024
Var
   A, B, C, delta: inteiro



Inicio
      Escreval("Dê um valor inteiro para A, B e C: ")
      Leia(A, B, C)
      Escreval("X= ", A, " + ", B, " + ", C, " =0")
      //Delta
      Delta <- ((B*B) -4) * A*C
      Escreval("O valor de delta é: ", Delta)


Fimalgoritmo