Algoritmo "Funcionário"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 04/01/2024
Var
// Seção de Declarações das variáveis 
   Nome: caractere
   Salario: Real

Inicio
      Escreval("Digite seu Nome: ")
      leia(Nome)
      Escreval("Digite seu Salátio: ")
      leia(Salario)
      Escreva("O funcionário ", Nome, " Recebe R$: ", Salario, " por mês")


Fimalgoritmo