Algoritmo "meu nome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 03/01/2024
Var
// Seção de Declarações das variáveis 
   nome:caractere

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
   escreval("escreva seu nome: ")
   leia (nome)
   escreva("muito prazer ", nome)



Fimalgoritmo