Algoritmo "par_Impar"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 11/01/2024
Var
     n: inteiro


Inicio
 escreval("Digite um numero: ")
   leia(n)

   se(n % 2 = 1) entao
             Escreva("O seu número é impar")
   senao
                   Escreva("O seu número é par")
   fimse


Fimalgoritmo