Algoritmo "Real_Dolar"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 04/01/2024
Var
   reais, dolar : Real


Inicio
      Escreval("Digite a quantia de dinheiro em Reais você tem na carteira")
      Leia(reais)
      //convertendo de real para dolar
      dolar<- reais /4.88
      Escreval("Você pode comprar ", dolar, " dolares com a quantia que você possui")


Fimalgoritmo