Algoritmo "Soma"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 04/01/2024
Var
   n1, n2, S: inteiro


Inicio
      escreval("Escreva um número: ")
      leia(n1)
      escreval("Escreva outro número: ")
      leia(n2)
      S<- n1+n2
      escreva("A soma entre ", n1, "e ", n2, "é ",s)

Fimalgoritmo
