Algoritmo "sucessor_antecessor"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 04/01/2024
Var
   numero, suc, ant: inteiro



Inicio
      escreval("DIgite um número: ")
      leia(numero)
      ant<- numero - 1
      escreval("O antecessor de ", numero, " é ",ant)
      suc<- numero +1
      escreval("O sucessor de ", numero," é ", suc)

      



Fimalgoritmo